name: flow123d
before-run: !readfile utils/setup_env.sh

git:
  - https://github.com/flow123d/flow123d.git
  - https://github.com/flow123d/bench_data.git

steps:
  - name: compile
    retries: 2
    stdout: true
    runs: !readfile utils/install.sh
    cache:
      - flow123d/build-<git.branch>
      - build-<git.branch>

  - name: test
    retries: 2
    stdout: true
    variables: !readyaml user/small-serial-set.yaml
    runs: !readfile  utils/runtest.sh
    collect: !readyaml user/collect.yaml
    # on-success: !readfile utils/delete-tmp.sh
    # on-failure: !readfile utils/delete-tmp.sh
