name: flow123d
before-run: !readfile utils/setup_env.sh

baselines:
  - commit: 6b54fcf046d36cb37bfcc53bd6e613eca1459bda
    title: 3.0.0
  - commit: b04af7fb08d423036b30ea00c3b8941b0c91e3c0
    title: 2.2.1
  - commit: f72c4b41f40db374168cc91ca59e6e7d87555596
    title: 3.0.2
  - commit: 4db4b481073edc73c22031aeb86c31c9b633025a
    title: 3.0.4

git:
  - https://github.com/flow123d/flow123d.git
  - https://github.com/flow123d/bench_data.git

steps:
  - name: compile
    retries: 4
    stdout: true
    runs: !readfile utils/install.sh
    cache:
      - flow123d/build-<git.branch>
      - build-<git.branch>

  - name: test
    retries: 3
    stdout: true
    variables: !readyaml user/small-serial-set.yaml
    runs:      !readfile utils/runtest.sh
    collect:   !readyaml user/collect.yaml
    # on-success: !readfile utils/delete-tmp.sh
    # on-failure: !readfile utils/delete-tmp.sh
