name: flow123d
before-run: |
  pwd

git:
  - https://github.com/flow123d/flow123d.git
  - https://github.com/flow123d/bench_data.git

steps:
  - name: compile
    runs: !readfile utils/install.sh
    cache:
      - flow123d/build-<git.branch>
      - build-<git.branch>

    # if: < get_output("flow123d/bin/flow123d --version").find(git.commit_short) != -1 >
  - name: test
    variables: !readyaml user/small-serial-set.yaml
    runs: !readfile  utils/runtest.sh
    collect: !readyaml user/collect.yaml
    on-success: !readfile utils/delete-tmp.sh
    on-failure: !readfile utils/delete-tmp.sh