name: Python application

on: [push]
env:
  PYTHONPATH:  src/

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov coveralls
        
    - name: Cache
      uses: actions/cache@v1.0.0
      with:
        path:  $HOME/.cache/pip
     
    - name: Test with pytest
      run: |
        py.test --cov=cihpc tests/integration/example-01/example_01.py
        
    - name: Coveralls
      run: |
        echo "repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}" > .coveralls.yml
        coveralls
